{{- if not .Values.meshAgent.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mesh-agent.fullname" . }}-auth
  labels:
    {{- include "mesh-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.meshAgent.authKey | quote }}
{{- end }}
